name: Python Linter

# Define triggers for the workflow
on:
  # Trigger the workflow when code is pushed to the 'main' branch
  push:
    branches:
      - main

  # Trigger the workflow manually from the Actions tab (workflow_dispatch)
  workflow_dispatch:

jobs:
  lint:
    name: Run Python Linter
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Adjust Python version if needed

      # Step 3: Run Python Linter
      - name: Python Linter
        uses: sunnysid3up/python-linter@v0.1-beta.7
