name: Pylint

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint anybadge

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') > pylint_output.txt || true

      - name: Print pylint_output.txt
        run: |
          cat pylint_output.txt

      - name: Generate pylint badge
        run: |
          score=$(grep 'Your code has been rated at' pylint_output.txt | grep -o '[0-9]*\.[0-9]*' | head -1)
          anybadge --value=$score --file=pylint.svg -o pylint

      - name: Print the svg badge
        run: |
          cat pylint.svg